"""powerfull

Revision ID: 2031f05a13fe
Revises: 
Create Date: 2019-12-22 09:40:50.078410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2031f05a13fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('profil', sa.String(length=100), nullable=False),
    sa.Column('profil_header', sa.String(length=100), nullable=False),
    sa.Column('profil_background', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('work', sa.String(length=100), nullable=False),
    sa.Column('education', sa.String(length=100), nullable=False),
    sa.Column('answersv1', sa.String(length=100), nullable=False),
    sa.Column('answersv2', sa.String(length=100), nullable=False),
    sa.Column('check_answersv1', sa.String(length=100), nullable=False),
    sa.Column('check_answersv2', sa.String(length=100), nullable=False),
    sa.Column('roles', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('check_password', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
